name: Build PDF and release
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for creating tags and releases
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
      - name: Create tag
        run: |
          TAG="math"
          git tag -f $TAG
          git push origin $TAG -f
      - name: Get timestamp
        run: echo "TIMESTAMP=$(date +'%Y-%m-%d %T')" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ env.TIMESTAMP }}
          tag_name: math
          files: main.pdf
          draft: false
